spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true


---
spring:
  profiles:
    active: server
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
