spring:
  h2: # 로컬
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  datasource: # 로컬
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:mem:test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa: #분리
    hibernate:
      ddl-auto: create-drop # 로컬, 서버는 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mail: #전체
  address:
    admin: admin@gmail.com

jwt: #전체
  key : ${JWT_SECRET_KEY}
  access-token-expiration-minutes : 30
  refresh-token-expiration-minutes : 420

logging: # 전체
  level:
    org.springframework.security: DEBUG