spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
