name: Java CI with Gradle

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: dreamconsumer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AdoptOpenJDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Prepare
        run: ./prepare.sh
        shell: bash

      - name: Build with Gradle
        run: ./server/gradlew build

      - name: Make zip file
        run: zip -r ./server/practice-deploy.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./server/practice-deploy.zip s3://$S3_BUCKET_NAME/practice-deploy.zip

      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name consumptionplanner
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name consumptionplanner-group
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=practice-deploy.zip
